# Generated by Django 6.0 on 2025-12-28 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=15, verbose_name='Movil')),
                ('email', models.EmailField(max_length=150, verbose_name='Email')),
                ('address', models.CharField(max_length=255, verbose_name='Direccion')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
            ],
            options={
                'verbose_name': 'Dato General',
                'verbose_name_plural': 'Generales',
                'ordering': ['-created_at'],
            },
        ),
    ]
