# Generated by Django 6.0 on 2025-12-30 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Titulo')),
                ('subtitle', models.CharField(max_length=100, verbose_name='Subtitulo')),
                ('imagen', models.ImageField(upload_to='carrousel/')),
                ('estado', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
            ],
            options={
                'verbose_name': 'Carrousel',
                'verbose_name_plural': 'Carrousels',
                'ordering': ['created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='miembros',
            options={'ordering': ['created_at'], 'verbose_name': 'Miembro', 'verbose_name_plural': 'Miembros'},
        ),
    ]
