# Generated by Django 6.0 on 2026-01-01 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titulo')),
                ('description', models.CharField(max_length=250, verbose_name='Descripción')),
                ('type_performance', models.CharField(choices=[('A', 'Acuerdo'), ('E', 'Evaluación')], max_length=1, verbose_name='Tipo')),
                ('file', models.FileField(upload_to='performance/', verbose_name='Archivo')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Desempeño',
                'verbose_name_plural': 'Informes de Desempeño',
                'ordering': ['-created_at'],
            },
        ),
    ]
