# Generated by Django 6.0 on 2026-01-01 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Norms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Norma Legal')),
                ('description', models.CharField(max_length=250, verbose_name='Descripción')),
                ('file', models.FileField(upload_to='norms/', verbose_name='Archivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
            ],
            options={
                'verbose_name': 'Norma Legal',
                'verbose_name_plural': 'Normas Legales',
                'ordering': ['created_at'],
            },
        ),
    ]
